name: CI
on: [ push, pull_request ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build release
        run: ./gradlew assembleRelease

      - uses: actions/upload-artifact@v2
        with:
          name: unsigned-app.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          if-no-files-found: error

  deploy:
    name: Deploy to GitHub Releases
    needs: build
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Get the APK
        uses: actions/download-artifact@v2
        with:
          name: unsigned-app.apk
          path: .

      - uses: r0adkll/sign-android-release@v1
        name: Sign the APK
        id: sign_app
        with:
          releaseDirectory: .
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Publish the APK to GitHub Releases
        uses: svenstaro/upload-release-action@v2
        with:
          prerelease: true
          asset_name: httptoolkit.apk
          file: ${{ steps.sign_app.outputs.signedReleaseFile }}
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish the APK to Google Play
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: tech.httptoolkit.android.v1
          releaseFiles: ${{ steps.sign_app.outputs.signedReleaseFile }}
          track: production
